spring:
  profiles:
    active: local

---
spring:
  datasource :
    url : jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username : prasad
    password : password
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-event-listener-group-1

server:
  port: 8081